### ISSUE TITLE
Feature Request: Ability to make tickers private

### ISSUE THREAD

**Issue by jamcat22** [hotmeteor/statusticker-support#101]
While I love the ability to share my ticker, it would also be nice to be able to make a private one so as not to advertise all the services used.

**Comment by hotmeteor** [comment]
@jamcat22 For sure. This is definitely something that will be added soon.

**Comment by hotmeteor** [comment]
Tickers can now be private!

![screen shot 2018-01-20 at 12 47 53 pm](https://user-images.githubusercontent.com/378585/35186831-42a65eb4-fde0-11e7-993d-6f91878f8ebc.png)
