### ISSUE TITLE
Forgot password link

### ISSUE THREAD

**Issue by nblackburn** [hotmeteor/statusticker-support#117]
![image](https://user-images.githubusercontent.com/2931085/89318590-e71ace00-d676-11ea-826e-7ce95845180b.png)

The forgot password link incorrectly links to the register page so it's impossible to recover your account.

**Comment by hotmeteor** [comment]
:| Sorry. Fixing now.

**Comment by hotmeteor** [comment]
@nblackburn This is fixed. My apologies.
