### ISSUE TITLE
New Service Requests: Vultr

### ISSUE THREAD

**Issue by jkniest** [hotmeteor/statusticker-support#5]
Hey,

Would it be possible to add support for vultr.com?

Have a nice day,
Jordan

**Comment by hotmeteor** [comment]
I'll look at it!

**Comment by jkniest** [comment]
I will leave this link here: https://www.vultr.com/status/

It's their official status page

Thank you :-)

**Comment by reinink** [comment]
Adam, you could even do something crazy and allow folks to choose which datacenter they can monitor. :feelsgood:

**Comment by hotmeteor** [comment]
Ya, some of these are tough because of the multiple data centers. Maybe that's the route to go. I have some other ideas.

**Comment by jkniest** [comment]
It would be the best if they could monitor multiple data center's, because some do have servers in multiple regions.

**Comment by hotmeteor** [comment]
@jkniest Finally got around to adding this one, sorry it took ~3 years.
