### ISSUE TITLE
Feature request: better UI for adding/managing services

### ISSUE THREAD

**Issue by jkudish** [hotmeteor/statusticker-support#58]
A few ideas that come to mind:

- [x] Having a separate page to manage services -- not loving the long scroll on the one page, and having to see services at the bottom of the page when I don't need to add anymore
- [x]  Would be nice to either: have these be a toggle w/ a save button OR be added via ajax calls. The page refresh when adding each service gets annoying
- [x] As more and more services get added, a search would be nice

**Comment by hotmeteor** [comment]
How many services do you really need to be monitoring at once though?

**Comment by jkudish** [comment]
It's more about the ease of use of setting them up then the number of them. Especially as you add support for more.

I currently have 25 in my account and will probably add a few more as you add more services :)

**Comment by hotmeteor** [comment]
Ya fair enough. TBH this is super early days, so there's lots of room to improve. I'll give it some love asap.

**Comment by jkudish** [comment]
No rush, it works as-is. Just some thoughts for future improvements :)

Thanks so much for putting this together and rocking the updates and quick response!

**Comment by hotmeteor** [comment]
Services can be dynamically added and removed now. Better UI for accessing new services coming soon.

**Comment by jkudish** [comment]
Awesome!
