### ISSUE TITLE
Question (or bug?): what determines warning vs. alert?

### ISSUE THREAD

**Issue by jkudish** [hotmeteor/statusticker-support#60]
For example, the Digital Ocean issue here:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/260253/33498437-321e01e0-d686-11e7-9760-474517a83ecc.png">

On their [own status page](https://status.digitalocean.com/) it's listed as "Degraded Performance" not as a critical alert so just curious why it's listed as an alert in StatusTicker

**Comment by hotmeteor** [comment]
That may have been categorized wrong, some of it is a bit up to interpretation. I noticed that one too, so I'll take a look ASAP.

**Comment by hotmeteor** [comment]
I've done a bunch of clean up and improvements around this and I think it's reflecting a much more accurate status. Thanks.
