### ISSUE TITLE
Feature Request: Public Profiles

### ISSUE THREAD

**Issue by codymcowan** [hotmeteor/statusticker-support#65]
Love this! Would be great to be able to make a collection of all the services my company uses and share it internally (or put it up on a screen somewhere in the office).

**Comment by hotmeteor** [comment]
Hey @codymcowan. That's sort of the point of the main Ticker page. Is there a different way you want that visualized?

**Comment by MerlinBB** [comment]
I think the issue is here that a ticker page isn't viewable to unauthenticated users... I've tried sending the link to a colleague but they get redirected to the login page.

**Comment by hotmeteor** [comment]
Ah right. I have this on my roadmap as a top priority.

**Comment by codymcowan** [comment]
Exactly - sharing with un-authed users

**Comment by hotmeteor** [comment]
@codymcowan Incoming...

**Comment by hotmeteor** [comment]
Aaaand it's live. Tickers are now publicly shareable. I'll probably add an option in the future to make it private, but hope that helps :)

**Comment by codymcowan** [comment]
thanks @hotmeteor !!
