### ISSUE TITLE
Feature Request: Notifications

### ISSUE THREAD

**Issue by jkniest** [hotmeteor/statusticker-support#7]
Hey,

first of all I am in love with your project already. But there is one thing I would really wish: Notifications. Maybe e-mail notifications or something like slack/sms notifications. Because I would like to know immediately when a service I am depending on (like Stripe for example) isn't reachable at the moment.

Of course I can hook into every status page of every service (with rss feeds for example) but I think your solution is way cleaner and nicer to use.

I hope you consider it!

Have a nice day,
Jordan

**Comment by jkudish** [comment]
I'd give you a few bucks a month for slack notifications whenever a service has a disruption and updated notification when it's back up

**Comment by hotmeteor** [comment]
Now available in Pro plan.
